# Generated by Django 4.2.3 on 2023-08-02 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=250)),
                ('Product_Description', models.CharField(max_length=250)),
                ('Product_Quantity', models.CharField(max_length=100)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Image', models.ImageField(null=True, upload_to='image/')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.categorymodal')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=250)),
                ('Phone_Number', models.CharField(max_length=250)),
                ('Customer_Image', models.ImageField(null=True, upload_to='image/')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.categorymodal')),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.productmodal')),
            ],
        ),
        migrations.CreateModel(
            name='CartModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.customermodal')),
                ('Cart_Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.productmodal')),
            ],
        ),
    ]
